save_dir: "./runs"
data_dir: "/home/pervinco/Datasets"
dataset_name: "CelebA"

epochs: 10
batch_size: 256
img_size: 64
d_lr: 0.0001
g_lr: 0.0001

mean: null
std: null

nc: 3
nz: 64
ndf: 256
ngf: 256

num_images: 64
