save_dir: "./runs"
data_dir: "/home/pervinco/Datasets"
dataset_name: "mnist"

model_name: "DCGAN"
init_weights: True
nc: 1
nz: 100
ndf: 64
ngf: 64
num_images: 64

epochs: 10
batch_size: 256
img_size: 64
d_lr: 0.0001
g_lr: 0.0001

mean: null
std: null
